version: '3.7'
services:
  app:
    volumes:
      - ./logs:/app/logs
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    env_file:
      - ./.env
    ports:
      - "7895:7895"
    networks:
      - nginx-proxy-manager-postgresql_default
networks:
  nginx-proxy-manager-postgresql_default:
    external: true
