version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7895:7895"
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium
    networks:
      - nginx-proxy-manager-postgresql_default

  selenium:
    image: selenium/standalone-firefox:4.27.0-20240226
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_START_VNC=true
    networks:
      - nginx-proxy-manager-postgresql_default
    shm_size: 2gb

networks:
  nginx-proxy-manager-postgresql_default:
    external: true