version: '3.8'

services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:99
    ports:
      - "7895:7895"
    command: >
      sh -c "Xvfb :99 -screen 0 1024x768x16 & java -jar app.jar"
    networks:
      - nginx-proxy-manager-postgresql_default
    depends_on:
      selenium:
        condition: service_healthy

  selenium:
    image: seleniarm/standalone-firefox:4.18.0-20240225
    platform: linux/arm64
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - nginx-proxy-manager-postgresql_default
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  nginx-proxy-manager-postgresql_default:
    external: true